FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build-env

WORKDIR /app

COPY Chefster.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build-env /app/out .

ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "Chefster.dll"]
