// <auto-generated />
using System;
using Chefster.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chefster.Migrations
{
    [DbContext(typeof(ChefsterDbContext))]
    [Migration("20241116203046_AddSubscriberModel")]
    partial class AddSubscriberModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Chefster.Models.AddressModel", b =>
                {
                    b.Property<string>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AptOrUnitNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityOrTown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateProvinceRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.ConsiderationsModel", b =>
                {
                    b.Property<string>("ConsiderationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConsiderationId");

                    b.ToTable("Considerations", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.FamilyModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenerationDay")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("GenerationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JobTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfBreakfastMeals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDinnerMeals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfLunchMeals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.JobRecordModel", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("JobRecords", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.MemberModel", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.PreviousRecipeModel", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Enjoyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("PreviousRecipes", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.SubscriberModel", b =>
                {
                    b.Property<string>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("FamilyId");

                    b.ToTable("Subscribers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
