// <auto-generated />
using System;
using Chefster.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chefster.Migrations
{
    [DbContext(typeof(ChefsterDbContext))]
    partial class ChefsterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Chefster.Models.ConsiderationsModel", b =>
                {
                    b.Property<string>("ConsiderationId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConsiderationId");

                    b.ToTable("Considerations", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.FamilyModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FamilySize")
                        .HasColumnType("int");

                    b.Property<int>("GenerationDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("GenerationTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("NumberOfBreakfastMeals")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDinnerMeals")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLunchMeals")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.MemberModel", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("MemberId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Chefster.Models.PreviousRecipeModel", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Enjoyed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecipeId");

                    b.ToTable("PreviousRecipes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
