name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build

    - name: Run tests
      run: |
        ls
        dotnet test Chefster.Tests/Chefster.Tests.csproj
