name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build

      - name: Run tests
        run: |
          dotnet test Tests/Tests.csproj

  deploy_to_ec2:
    needs: run_unit_tests
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Build project
        run: dotnet publish -c Release -o app

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.EC2_HOST_NAME }}
          USER_NAME: ${{ secrets.EC2_USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -v -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} `
            sudo rm -rf /var/www/*
            sudo rm -rf /etc/systemd/system/chefster.service
            exit
          `
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" chefster.service ${USER_NAME}@${HOST_NAME}:/etc/systemd/system --rsync-path="sudo rsync"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" ./app/ ${USER_NAME}@${HOST_NAME}:/var/www/ --rsync-path="sudo rsync"
          ssh -v -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
            sudo systemctl stop chefster.service
            sudo systemctl start chefster.service
            exit
          '
      - name: Cleanup
        run: rm -f private_key
